COL-596: [Livesync Integration] Issue view
ably-labs/models pull request #138
Opened 2023-12-26 16:41 UTC by snikidev

2024-01-15 11:01 UTC, mschristensen commented on examples/livesync/components/Drawer/Comments.tsx
> +      data,
I have created a ticket to support event type inference in the library: https://ably.atlassian.net/browse/COL-652

2024-01-15 11:01 UTC, mschristensen commented on examples/livesync/components/Drawer/Comments.tsx
> +      cancel();
Let's log the error

2024-01-17 12:27 UTC, snikidev commented on examples/livesync/components/modelsClient/useCommentsModel.ts
> +  useEffect(() => {
Technically we can, but I think in React world it's usually preferred to separate different functionalities into different useEffects hooks https://stackoverflow.com/a/54004148/5650901

2024-01-17 13:01 UTC, snikidev commented on examples/livesync/components/modelsClient/useCommentsModel.ts
> +      // @ts-ignore - types to be fixed for merge functions later
What do you mean by `mark the merge function async`? I don't think I can have `Promise` as a return type and return an object from there.It's gonna give me the error in a different place.

2024-01-17 13:21 UTC, snikidev commented on examples/livesync/app/utils.ts
> +    const projects = await sql<ProjectType[]>`SELECT * FROM projects WHERE slug = ${slug}`;
In case of an error, i.e. no project, I added redirect to `/` so that it could take over and redirect to an existing project

2024-01-25 16:39 UTC, snikidev commented on examples/livesync/components/Drawer/Comments.tsx
> +    }
About `.then()`, not sure I get the question, but I think it's more of a `Promise` way of doing things, while we're doing async/await here. 

Technically we can do `.then()` but we'd be mixing those two approaches. :) 
https://dev.to/masteringjs/using-then-vs-async-await-in-javascript-2pma

2024-01-25 16:40 UTC, snikidev commented on examples/livesync/docker-compose.yml
> +  #     adbc_network:
I did this for @mschristensen. So yeah, I'm not sure if we wanna keep it or leave it in case anyone wants to launch it all in docker too 🤷

2024-01-25 16:41 UTC, snikidev commented on examples/livesync/README.md
> +If you simply would like to run the app on your machine and do not plan to make any changes or anything, simply go to `docker-compose.yml` file, uncomment the `app` service, and run
Sure, I'll remove it. It's simply SIMPLE! 😂

2024-01-25 16:43 UTC, snikidev commented on examples/livesync/README.md
> +**NOTE**: Don't forget to make `ADBC_POSTGRES_CONNECTION_URI` variable back to `localhost:5432` before you run the app scripts.
That's because I couldn't figure out how to do docker command with `localhost` string and launch the front-end with the `postgres` string 😂

2024-01-26 09:27 UTC, mschristensen commented on examples/livesync/components/Drawer/Comments.tsx
> +    }
>If all we do is cancel() on error

We cancel if the backend update fails OR is never confirmed/is explicitly rejected. So I think this code is good

2024-01-26 10:09 UTC, mschristensen approved these changes
I think we should fix the dockerfile comments zak mentioned, but once fixed this looks good :+1:

2024-01-30 18:40 UTC, mschristensen requested changes
Looks good we just need to fix the dockerfile bit :)

2024-01-30 18:40 UTC, mschristensen commented on examples/livesync/Dockerfile
> +ENTRYPOINT ["/docker-entrypoint.sh"]
Why do we need a separate `ENTRYPOINT` and `CMD`? Seems to me unclear how the user is intended to start the container.

Instead we could just do a `RUN pnpm build` and a `CMD pnpm seed && pnpm start` ?

But - do we always want to seed the database when starting the app container? Istm we should do that when we start the postgres container instead?

2024-02-07 09:28 UTC, mschristensen requested changes

2024-02-07 09:28 UTC, mschristensen commented on examples/livesync/Dockerfile
> +RUN IS_DOCKER=true
This isn't quite right - this makes the env available in the build stage but not at runtime.

To get it to work, you have to include `IS_DOCKER=true` in the env file. We can then remove it from here.

2024-02-07 09:56 UTC, mschristensen approved these changes

2024-02-07 09:58 UTC, merged