COL-595: Error on getting channel with 'agent' params if user has already 'got' the channel
ably-labs/models pull request #155
Opened 2024-02-20 09:59 UTC by snikidev

2024-02-28 16:04 UTC, zknill approved these changes

2024-03-04 16:34 UTC, mschristensen requested changes

2024-03-04 16:34 UTC, mschristensen commented on src/stream/Stream.test.ts
> +    channel.setOptions = vi.fn();
Let's set this by default on the `mockChannel` set up before the tests run.

2024-03-06 10:22 UTC, snikidev commented on src/utilities/test/createAblyApp.ts
> +import ky from 'ky';
Nope. `ky` is good for server as well, I just forgot that we only use it in tests 😅

2024-03-07 12:30 UTC, mschristensen commented on src/stream/Stream.integration.test.ts
> +          presence: [
It doesn't look like we need a presence set for this test?

2024-03-12 10:34 UTC, merged